# Template
START_SIGN = '0002'
PROTOCOL_VERSION = '01'
END_SIGN = '0003'

# Fields
BITMAP_INDEX = 1
BITMAP_LENGTH = 4

TRANSACTION_ID_INDEX = 2
TRANSACTION_ID_LENGTH = 4

PAN_INDEX = 3
PAN_LENGTH = 16

CARDHOLDER_NAME_INDEX = 4
# CARDHOLDER_NAME_LENGTH vary

EXPIRY_DATE_INDEX = 5
EXPIRY_DATE_LENGTH = 4

PIN_INDEX = 6
PIN_LENGTH = 4

AMOUNT_INDEX = 7
AMOUNT_LENGTH = 12

TRANSACTION_NO_INDEX = 8
TRANSACTION_NO_LENGTH = 10

RRN_INDEX = 9
RRN_LENGTH = 12

TEXT_DATA_INDEX = 10
TEXT_DATA_LENGTH = 30

TERMINAL_ID_INDEX = 11
TERMINAL_ID_LENGTH = 10

# never used
# RC_INDEX = 12
# RC_LENGTH = 4

DATETIME_INDEX = 13
DATETIME_LENGTH = 10

CRC_INDEX = 14
CRC_LENGTH = 8

__lengths__ = {
    BITMAP_INDEX: BITMAP_LENGTH,
    TRANSACTION_ID_INDEX: TRANSACTION_ID_LENGTH,
    PAN_INDEX: PAN_LENGTH,
    EXPIRY_DATE_INDEX: EXPIRY_DATE_LENGTH,
    PIN_INDEX: PIN_LENGTH,
    AMOUNT_INDEX: AMOUNT_LENGTH,
    TRANSACTION_NO_INDEX: TRANSACTION_NO_LENGTH,
    RRN_INDEX: RRN_LENGTH,
    TEXT_DATA_INDEX: TEXT_DATA_LENGTH,
    TERMINAL_ID_INDEX: TERMINAL_ID_LENGTH,
    DATETIME_INDEX: DATETIME_LENGTH,
    CRC_INDEX: CRC_LENGTH
}






