# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Model(object):
    def setupUi(self, Model):
        Model.setObjectName("Model")
        Model.resize(781, 619)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Model.sizePolicy().hasHeightForWidth())
        Model.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Model)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.modelTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.modelTabs.setObjectName("modelTabs")
        self.transactionTab = QtWidgets.QWidget()
        self.transactionTab.setObjectName("transactionTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.transactionTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.transactionLayout = QtWidgets.QVBoxLayout()
        self.transactionLayout.setObjectName("transactionLayout")
        self.transactionDataTable = QtWidgets.QTableWidget(self.transactionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transactionDataTable.sizePolicy().hasHeightForWidth())
        self.transactionDataTable.setSizePolicy(sizePolicy)
        self.transactionDataTable.setObjectName("transactionDataTable")
        self.transactionDataTable.setColumnCount(16)
        self.transactionDataTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 15, item)
        self.transactionDataTable.horizontalHeader().setDefaultSectionSize(40)
        self.transactionLayout.addWidget(self.transactionDataTable)
        self.tableDataLabel = QtWidgets.QLabel(self.transactionTab)
        self.tableDataLabel.setObjectName("tableDataLabel")
        self.transactionLayout.addWidget(self.tableDataLabel)
        self.transactionValuesLayout = QtWidgets.QHBoxLayout()
        self.transactionValuesLayout.setObjectName("transactionValuesLayout")
        self.protocolLayout = QtWidgets.QVBoxLayout()
        self.protocolLayout.setSpacing(0)
        self.protocolLayout.setObjectName("protocolLayout")
        self.methodlabel = QtWidgets.QLabel(self.transactionTab)
        self.methodlabel.setObjectName("methodlabel")
        self.protocolLayout.addWidget(self.methodlabel)
        self.methodRadioButton = QtWidgets.QRadioButton(self.transactionTab)
        self.methodRadioButton.setObjectName("methodRadioButton")
        self.protocolLayout.addWidget(self.methodRadioButton)
        self.startSignLabel = QtWidgets.QLabel(self.transactionTab)
        self.startSignLabel.setObjectName("startSignLabel")
        self.protocolLayout.addWidget(self.startSignLabel)
        self.startSignComboBox = QtWidgets.QComboBox(self.transactionTab)
        self.startSignComboBox.setEditable(False)
        self.startSignComboBox.setObjectName("startSignComboBox")
        self.startSignComboBox.addItem("")
        self.protocolLayout.addWidget(self.startSignComboBox)
        self.protocolVersionLabel = QtWidgets.QLabel(self.transactionTab)
        self.protocolVersionLabel.setObjectName("protocolVersionLabel")
        self.protocolLayout.addWidget(self.protocolVersionLabel)
        self.protocolVersionComboBox = QtWidgets.QComboBox(self.transactionTab)
        self.protocolVersionComboBox.setObjectName("protocolVersionComboBox")
        self.protocolVersionComboBox.addItem("")
        self.protocolLayout.addWidget(self.protocolVersionComboBox)
        self.endSignLabel = QtWidgets.QLabel(self.transactionTab)
        self.endSignLabel.setObjectName("endSignLabel")
        self.protocolLayout.addWidget(self.endSignLabel)
        self.endSignComboBox = QtWidgets.QComboBox(self.transactionTab)
        self.endSignComboBox.setObjectName("endSignComboBox")
        self.endSignComboBox.addItem("")
        self.protocolLayout.addWidget(self.endSignComboBox)
        self.transactionValuesLayout.addLayout(self.protocolLayout)
        self.cardLayout = QtWidgets.QVBoxLayout()
        self.cardLayout.setSpacing(0)
        self.cardLayout.setObjectName("cardLayout")
        self.panLabel = QtWidgets.QLabel(self.transactionTab)
        self.panLabel.setObjectName("panLabel")
        self.cardLayout.addWidget(self.panLabel)
        self.panLineEdit = QtWidgets.QLineEdit(self.transactionTab)
        self.panLineEdit.setObjectName("panLineEdit")
        self.cardLayout.addWidget(self.panLineEdit)
        self.nameLabel = QtWidgets.QLabel(self.transactionTab)
        self.nameLabel.setObjectName("nameLabel")
        self.cardLayout.addWidget(self.nameLabel)
        self.carhholderNameEdit = QtWidgets.QLineEdit(self.transactionTab)
        self.carhholderNameEdit.setObjectName("carhholderNameEdit")
        self.cardLayout.addWidget(self.carhholderNameEdit)
        self.pinLabel = QtWidgets.QLabel(self.transactionTab)
        self.pinLabel.setObjectName("pinLabel")
        self.cardLayout.addWidget(self.pinLabel)
        self.pinLineEdit = QtWidgets.QLineEdit(self.transactionTab)
        self.pinLineEdit.setObjectName("pinLineEdit")
        self.cardLayout.addWidget(self.pinLineEdit)
        self.expDateLabel = QtWidgets.QLabel(self.transactionTab)
        self.expDateLabel.setObjectName("expDateLabel")
        self.cardLayout.addWidget(self.expDateLabel)
        self.expDateEdit = QtWidgets.QDateEdit(self.transactionTab)
        self.expDateEdit.setDate(QtCore.QDate(2020, 1, 1))
        self.expDateEdit.setObjectName("expDateEdit")
        self.cardLayout.addWidget(self.expDateEdit)
        self.transactionValuesLayout.addLayout(self.cardLayout)
        self.textDataLayout = QtWidgets.QVBoxLayout()
        self.textDataLayout.setSpacing(0)
        self.textDataLayout.setObjectName("textDataLayout")
        self.textDataLabel = QtWidgets.QLabel(self.transactionTab)
        self.textDataLabel.setObjectName("textDataLabel")
        self.textDataLayout.addWidget(self.textDataLabel)
        self.textDataPlainTextEdit = QtWidgets.QPlainTextEdit(self.transactionTab)
        self.textDataPlainTextEdit.setObjectName("textDataPlainTextEdit")
        self.textDataLayout.addWidget(self.textDataPlainTextEdit)
        self.transactionValuesLayout.addLayout(self.textDataLayout)
        self.transactionValuesLayout.setStretch(0, 1)
        self.transactionValuesLayout.setStretch(1, 1)
        self.transactionValuesLayout.setStretch(2, 1)
        self.transactionLayout.addLayout(self.transactionValuesLayout)
        self.terminalButtonsLayout = QtWidgets.QHBoxLayout()
        self.terminalButtonsLayout.setObjectName("terminalButtonsLayout")
        self.testTransactionButton = QtWidgets.QPushButton(self.transactionTab)
        self.testTransactionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.testTransactionButton.setObjectName("testTransactionButton")
        self.terminalButtonsLayout.addWidget(self.testTransactionButton)
        self.saleTransactionButton = QtWidgets.QPushButton(self.transactionTab)
        self.saleTransactionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saleTransactionButton.setObjectName("saleTransactionButton")
        self.terminalButtonsLayout.addWidget(self.saleTransactionButton)
        self.refundTransactionButton = QtWidgets.QPushButton(self.transactionTab)
        self.refundTransactionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refundTransactionButton.setObjectName("refundTransactionButton")
        self.terminalButtonsLayout.addWidget(self.refundTransactionButton)
        self.balanceTransactionButton = QtWidgets.QPushButton(self.transactionTab)
        self.balanceTransactionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.balanceTransactionButton.setObjectName("balanceTransactionButton")
        self.terminalButtonsLayout.addWidget(self.balanceTransactionButton)
        self.settlementTransactionButton = QtWidgets.QPushButton(self.transactionTab)
        self.settlementTransactionButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settlementTransactionButton.setObjectName("settlementTransactionButton")
        self.terminalButtonsLayout.addWidget(self.settlementTransactionButton)
        self.transactionLayout.addLayout(self.terminalButtonsLayout)
        self.verticalLayout_4.addLayout(self.transactionLayout)
        self.modelTabs.addTab(self.transactionTab, "")
        self.termialTab = QtWidgets.QWidget()
        self.termialTab.setObjectName("termialTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.termialTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.terminalLayout = QtWidgets.QVBoxLayout()
        self.terminalLayout.setObjectName("terminalLayout")
        self.terminalLog = QtWidgets.QLabel(self.termialTab)
        self.terminalLog.setObjectName("terminalLog")
        self.terminalLayout.addWidget(self.terminalLog)
        self.terminalLogList = QtWidgets.QListWidget(self.termialTab)
        self.terminalLogList.setObjectName("terminalLogList")
        self.terminalLayout.addWidget(self.terminalLogList)
        self.verticalLayout_10.addLayout(self.terminalLayout)
        self.modelTabs.addTab(self.termialTab, "")
        self.mainLayout.addWidget(self.modelTabs)
        self.horizontalLayout.addLayout(self.mainLayout)
        Model.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Model)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 22))
        self.menubar.setObjectName("menubar")
        Model.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Model)
        self.statusbar.setObjectName("statusbar")
        Model.setStatusBar(self.statusbar)

        self.retranslateUi(Model)
        self.modelTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Model)

    def retranslateUi(self, Model):
        _translate = QtCore.QCoreApplication.translate
        Model.setWindowTitle(_translate("Model", "Model"))
        item = self.transactionDataTable.verticalHeaderItem(0)
        item.setText(_translate("Model", "00000000"))
        item = self.transactionDataTable.verticalHeaderItem(1)
        item.setText(_translate("Model", "00000010"))
        item = self.transactionDataTable.verticalHeaderItem(2)
        item.setText(_translate("Model", "00000020"))
        item = self.transactionDataTable.verticalHeaderItem(3)
        item.setText(_translate("Model", "00000030"))
        item = self.transactionDataTable.verticalHeaderItem(4)
        item.setText(_translate("Model", "00000040"))
        item = self.transactionDataTable.verticalHeaderItem(5)
        item.setText(_translate("Model", "00000050"))
        item = self.transactionDataTable.verticalHeaderItem(6)
        item.setText(_translate("Model", "00000060"))
        item = self.transactionDataTable.verticalHeaderItem(7)
        item.setText(_translate("Model", "00000070"))
        item = self.transactionDataTable.verticalHeaderItem(8)
        item.setText(_translate("Model", "00000080"))
        item = self.transactionDataTable.verticalHeaderItem(9)
        item.setText(_translate("Model", "00000090"))
        item = self.transactionDataTable.horizontalHeaderItem(0)
        item.setText(_translate("Model", "00"))
        item = self.transactionDataTable.horizontalHeaderItem(1)
        item.setText(_translate("Model", "01"))
        item = self.transactionDataTable.horizontalHeaderItem(2)
        item.setText(_translate("Model", "02"))
        item = self.transactionDataTable.horizontalHeaderItem(3)
        item.setText(_translate("Model", "03"))
        item = self.transactionDataTable.horizontalHeaderItem(4)
        item.setText(_translate("Model", "04"))
        item = self.transactionDataTable.horizontalHeaderItem(5)
        item.setText(_translate("Model", "05"))
        item = self.transactionDataTable.horizontalHeaderItem(6)
        item.setText(_translate("Model", "06"))
        item = self.transactionDataTable.horizontalHeaderItem(7)
        item.setText(_translate("Model", "07"))
        item = self.transactionDataTable.horizontalHeaderItem(8)
        item.setText(_translate("Model", "08"))
        item = self.transactionDataTable.horizontalHeaderItem(9)
        item.setText(_translate("Model", "09"))
        item = self.transactionDataTable.horizontalHeaderItem(10)
        item.setText(_translate("Model", "0A"))
        item = self.transactionDataTable.horizontalHeaderItem(11)
        item.setText(_translate("Model", "0B"))
        item = self.transactionDataTable.horizontalHeaderItem(12)
        item.setText(_translate("Model", "0C"))
        item = self.transactionDataTable.horizontalHeaderItem(13)
        item.setText(_translate("Model", "0D"))
        item = self.transactionDataTable.horizontalHeaderItem(14)
        item.setText(_translate("Model", "0E"))
        item = self.transactionDataTable.horizontalHeaderItem(15)
        item.setText(_translate("Model", "0F"))
        __sortingEnabled = self.transactionDataTable.isSortingEnabled()
        self.transactionDataTable.setSortingEnabled(False)
        item = self.transactionDataTable.item(0, 0)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(0, 1)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(0, 2)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(0, 3)
        item.setText(_translate("Model", "32"))
        item = self.transactionDataTable.item(0, 4)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(0, 5)
        item.setText(_translate("Model", "31"))
        self.transactionDataTable.setSortingEnabled(__sortingEnabled)
        self.tableDataLabel.setText(_translate("Model", "Transaction data will be displayed here...."))
        self.methodlabel.setText(_translate("Model", "Method"))
        self.methodRadioButton.setText(_translate("Model", "From fields"))
        self.startSignLabel.setText(_translate("Model", "Start Sign"))
        self.startSignComboBox.setItemText(0, _translate("Model", "0002"))
        self.protocolVersionLabel.setText(_translate("Model", "Protocol Version"))
        self.protocolVersionComboBox.setItemText(0, _translate("Model", "01"))
        self.endSignLabel.setText(_translate("Model", "End Sign"))
        self.endSignComboBox.setItemText(0, _translate("Model", "0003"))
        self.panLabel.setText(_translate("Model", "PAN"))
        self.nameLabel.setText(_translate("Model", "Cardholder Name"))
        self.pinLabel.setText(_translate("Model", "PIN"))
        self.expDateLabel.setText(_translate("Model", "Expiry Date"))
        self.expDateEdit.setDisplayFormat(_translate("Model", "MM/yy"))
        self.textDataLabel.setText(_translate("Model", "Text Data"))
        self.testTransactionButton.setText(_translate("Model", "Test"))
        self.saleTransactionButton.setText(_translate("Model", "Sale"))
        self.refundTransactionButton.setText(_translate("Model", "Refund"))
        self.balanceTransactionButton.setText(_translate("Model", "Balance"))
        self.settlementTransactionButton.setText(_translate("Model", "Settlement"))
        self.modelTabs.setTabText(self.modelTabs.indexOf(self.transactionTab), _translate("Model", "Transaction"))
        self.terminalLog.setText(_translate("Model", "Terminal Log"))
        self.modelTabs.setTabText(self.modelTabs.indexOf(self.termialTab), _translate("Model", "Terminal"))
