# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Model(object):
    def setupUi(self, Model):
        Model.setObjectName("Model")
        Model.resize(786, 497)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Model.sizePolicy().hasHeightForWidth())
        Model.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Model)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.modelTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.modelTabs.setObjectName("modelTabs")
        self.clientTab = QtWidgets.QWidget()
        self.clientTab.setObjectName("clientTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.clientTab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.clientLayout = QtWidgets.QVBoxLayout()
        self.clientLayout.setObjectName("clientLayout")
        self.verticalLayout_5.addLayout(self.clientLayout)
        self.modelTabs.addTab(self.clientTab, "")
        self.transactionTab = QtWidgets.QWidget()
        self.transactionTab.setObjectName("transactionTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.transactionTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.transactionLayout = QtWidgets.QVBoxLayout()
        self.transactionLayout.setObjectName("transactionLayout")
        self.transactionDataTable = QtWidgets.QTableWidget(self.transactionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transactionDataTable.sizePolicy().hasHeightForWidth())
        self.transactionDataTable.setSizePolicy(sizePolicy)
        self.transactionDataTable.setObjectName("transactionDataTable")
        self.transactionDataTable.setColumnCount(16)
        self.transactionDataTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 13, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 14, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(0, 15, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 11, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 12, item)
        item = QtWidgets.QTableWidgetItem()
        self.transactionDataTable.setItem(1, 13, item)
        self.transactionDataTable.horizontalHeader().setDefaultSectionSize(40)
        self.transactionLayout.addWidget(self.transactionDataTable)
        self.transactionValuesLayout = QtWidgets.QHBoxLayout()
        self.transactionValuesLayout.setObjectName("transactionValuesLayout")
        self.startSignLayout = QtWidgets.QVBoxLayout()
        self.startSignLayout.setObjectName("startSignLayout")
        self.startSignLabel = QtWidgets.QLabel(self.transactionTab)
        self.startSignLabel.setObjectName("startSignLabel")
        self.startSignLayout.addWidget(self.startSignLabel)
        self.startSignComboBox = QtWidgets.QComboBox(self.transactionTab)
        self.startSignComboBox.setObjectName("startSignComboBox")
        self.startSignComboBox.addItem("")
        self.startSignLayout.addWidget(self.startSignComboBox)
        self.transactionValuesLayout.addLayout(self.startSignLayout)
        self.protocolVersionLayout = QtWidgets.QVBoxLayout()
        self.protocolVersionLayout.setObjectName("protocolVersionLayout")
        self.protocolVersionLabel = QtWidgets.QLabel(self.transactionTab)
        self.protocolVersionLabel.setObjectName("protocolVersionLabel")
        self.protocolVersionLayout.addWidget(self.protocolVersionLabel)
        self.protocolVersionComboBox = QtWidgets.QComboBox(self.transactionTab)
        self.protocolVersionComboBox.setObjectName("protocolVersionComboBox")
        self.protocolVersionComboBox.addItem("")
        self.protocolVersionLayout.addWidget(self.protocolVersionComboBox)
        self.transactionValuesLayout.addLayout(self.protocolVersionLayout)
        self.endSignLayout = QtWidgets.QVBoxLayout()
        self.endSignLayout.setObjectName("endSignLayout")
        self.endSignLabel = QtWidgets.QLabel(self.transactionTab)
        self.endSignLabel.setObjectName("endSignLabel")
        self.endSignLayout.addWidget(self.endSignLabel)
        self.endSignComboBox = QtWidgets.QComboBox(self.transactionTab)
        self.endSignComboBox.setObjectName("endSignComboBox")
        self.endSignComboBox.addItem("")
        self.endSignLayout.addWidget(self.endSignComboBox)
        self.transactionValuesLayout.addLayout(self.endSignLayout)
        self.transactionLayout.addLayout(self.transactionValuesLayout)
        self.transactionDataLabel = QtWidgets.QLabel(self.transactionTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transactionDataLabel.sizePolicy().hasHeightForWidth())
        self.transactionDataLabel.setSizePolicy(sizePolicy)
        self.transactionDataLabel.setObjectName("transactionDataLabel")
        self.transactionLayout.addWidget(self.transactionDataLabel)
        self.transactionDataLineEdit = QtWidgets.QLineEdit(self.transactionTab)
        self.transactionDataLineEdit.setObjectName("transactionDataLineEdit")
        self.transactionLayout.addWidget(self.transactionDataLineEdit)
        self.tarminalButtonsLayout = QtWidgets.QHBoxLayout()
        self.tarminalButtonsLayout.setObjectName("tarminalButtonsLayout")
        self.makeTransactionButton = QtWidgets.QPushButton(self.transactionTab)
        self.makeTransactionButton.setObjectName("makeTransactionButton")
        self.tarminalButtonsLayout.addWidget(self.makeTransactionButton)
        self.stopTransactionButton = QtWidgets.QPushButton(self.transactionTab)
        self.stopTransactionButton.setObjectName("stopTransactionButton")
        self.tarminalButtonsLayout.addWidget(self.stopTransactionButton)
        self.cancelTransactionButton = QtWidgets.QPushButton(self.transactionTab)
        self.cancelTransactionButton.setObjectName("cancelTransactionButton")
        self.tarminalButtonsLayout.addWidget(self.cancelTransactionButton)
        self.transactionLayout.addLayout(self.tarminalButtonsLayout)
        self.verticalLayout_4.addLayout(self.transactionLayout)
        self.modelTabs.addTab(self.transactionTab, "")
        self.termialTab = QtWidgets.QWidget()
        self.termialTab.setObjectName("termialTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.termialTab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.terminalLayout = QtWidgets.QVBoxLayout()
        self.terminalLayout.setObjectName("terminalLayout")
        self.terminalLogList = QtWidgets.QListView(self.termialTab)
        self.terminalLogList.setObjectName("terminalLogList")
        self.terminalLayout.addWidget(self.terminalLogList)
        self.verticalLayout_10.addLayout(self.terminalLayout)
        self.modelTabs.addTab(self.termialTab, "")
        self.serverTab = QtWidgets.QWidget()
        self.serverTab.setObjectName("serverTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.serverTab)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.serverLayout = QtWidgets.QVBoxLayout()
        self.serverLayout.setObjectName("serverLayout")
        self.serverLogList = QtWidgets.QListWidget(self.serverTab)
        self.serverLogList.setObjectName("serverLogList")
        self.serverLayout.addWidget(self.serverLogList)
        self.horizontalLayout_3.addLayout(self.serverLayout)
        self.modelTabs.addTab(self.serverTab, "")
        self.mainLayout.addWidget(self.modelTabs)
        self.horizontalLayout.addLayout(self.mainLayout)
        Model.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Model)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 22))
        self.menubar.setObjectName("menubar")
        Model.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Model)
        self.statusbar.setObjectName("statusbar")
        Model.setStatusBar(self.statusbar)

        self.retranslateUi(Model)
        self.modelTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Model)

    def retranslateUi(self, Model):
        _translate = QtCore.QCoreApplication.translate
        Model.setWindowTitle(_translate("Model", "Model"))
        self.modelTabs.setTabText(self.modelTabs.indexOf(self.clientTab), _translate("Model", "Shop"))
        item = self.transactionDataTable.verticalHeaderItem(0)
        item.setText(_translate("Model", "00000000"))
        item = self.transactionDataTable.verticalHeaderItem(1)
        item.setText(_translate("Model", "00000010"))
        item = self.transactionDataTable.horizontalHeaderItem(0)
        item.setText(_translate("Model", "00"))
        item = self.transactionDataTable.horizontalHeaderItem(1)
        item.setText(_translate("Model", "01"))
        item = self.transactionDataTable.horizontalHeaderItem(2)
        item.setText(_translate("Model", "02"))
        item = self.transactionDataTable.horizontalHeaderItem(3)
        item.setText(_translate("Model", "03"))
        item = self.transactionDataTable.horizontalHeaderItem(4)
        item.setText(_translate("Model", "04"))
        item = self.transactionDataTable.horizontalHeaderItem(5)
        item.setText(_translate("Model", "05"))
        item = self.transactionDataTable.horizontalHeaderItem(6)
        item.setText(_translate("Model", "06"))
        item = self.transactionDataTable.horizontalHeaderItem(7)
        item.setText(_translate("Model", "07"))
        item = self.transactionDataTable.horizontalHeaderItem(8)
        item.setText(_translate("Model", "08"))
        item = self.transactionDataTable.horizontalHeaderItem(9)
        item.setText(_translate("Model", "09"))
        item = self.transactionDataTable.horizontalHeaderItem(10)
        item.setText(_translate("Model", "0A"))
        item = self.transactionDataTable.horizontalHeaderItem(11)
        item.setText(_translate("Model", "0B"))
        item = self.transactionDataTable.horizontalHeaderItem(12)
        item.setText(_translate("Model", "0C"))
        item = self.transactionDataTable.horizontalHeaderItem(13)
        item.setText(_translate("Model", "0D"))
        item = self.transactionDataTable.horizontalHeaderItem(14)
        item.setText(_translate("Model", "0E"))
        item = self.transactionDataTable.horizontalHeaderItem(15)
        item.setText(_translate("Model", "0F"))
        __sortingEnabled = self.transactionDataTable.isSortingEnabled()
        self.transactionDataTable.setSortingEnabled(False)
        item = self.transactionDataTable.item(0, 0)
        item.setText(_translate("Model", "11"))
        item = self.transactionDataTable.item(0, 1)
        item.setText(_translate("Model", "4C"))
        item = self.transactionDataTable.item(0, 2)
        item.setText(_translate("Model", "45"))
        item = self.transactionDataTable.item(0, 3)
        item.setText(_translate("Model", "4F"))
        item = self.transactionDataTable.item(0, 4)
        item.setText(_translate("Model", "4E"))
        item = self.transactionDataTable.item(0, 5)
        item.setText(_translate("Model", "41"))
        item = self.transactionDataTable.item(0, 6)
        item.setText(_translate("Model", "52"))
        item = self.transactionDataTable.item(0, 7)
        item.setText(_translate("Model", "44"))
        item = self.transactionDataTable.item(0, 8)
        item.setText(_translate("Model", "4F"))
        item = self.transactionDataTable.item(0, 9)
        item.setText(_translate("Model", "20"))
        item = self.transactionDataTable.item(0, 10)
        item.setText(_translate("Model", "44"))
        item = self.transactionDataTable.item(0, 11)
        item.setText(_translate("Model", "41"))
        item = self.transactionDataTable.item(0, 12)
        item.setText(_translate("Model", "20"))
        item = self.transactionDataTable.item(0, 13)
        item.setText(_translate("Model", "56"))
        item = self.transactionDataTable.item(0, 14)
        item.setText(_translate("Model", "49"))
        item = self.transactionDataTable.item(0, 15)
        item.setText(_translate("Model", "4E"))
        item = self.transactionDataTable.item(1, 0)
        item.setText(_translate("Model", "43"))
        item = self.transactionDataTable.item(1, 1)
        item.setText(_translate("Model", "49"))
        item = self.transactionDataTable.item(1, 2)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(1, 3)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(1, 4)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(1, 5)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(1, 6)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(1, 7)
        item.setText(_translate("Model", "30"))
        item = self.transactionDataTable.item(1, 8)
        item.setText(_translate("Model", "31"))
        item = self.transactionDataTable.item(1, 9)
        item.setText(_translate("Model", "32"))
        item = self.transactionDataTable.item(1, 10)
        item.setText(_translate("Model", "33"))
        item = self.transactionDataTable.item(1, 11)
        item.setText(_translate("Model", "34"))
        item = self.transactionDataTable.item(1, 12)
        item.setText(_translate("Model", "35"))
        item = self.transactionDataTable.item(1, 13)
        item.setText(_translate("Model", "36"))
        self.transactionDataTable.setSortingEnabled(__sortingEnabled)
        self.startSignLabel.setText(_translate("Model", "Start Sign"))
        self.startSignComboBox.setItemText(0, _translate("Model", "0002"))
        self.protocolVersionLabel.setText(_translate("Model", "Protocol Version"))
        self.protocolVersionComboBox.setItemText(0, _translate("Model", "01"))
        self.endSignLabel.setText(_translate("Model", "End Sign"))
        self.endSignComboBox.setItemText(0, _translate("Model", "0003"))
        self.transactionDataLabel.setText(_translate("Model", "Transaction Data"))
        self.transactionDataLineEdit.setText(_translate("Model", ".LEONARDODAVINCI000000123456"))
        self.makeTransactionButton.setText(_translate("Model", "Make Transaction"))
        self.stopTransactionButton.setText(_translate("Model", "Stop Transaction"))
        self.cancelTransactionButton.setText(_translate("Model", "Cancel Transaction"))
        self.modelTabs.setTabText(self.modelTabs.indexOf(self.transactionTab), _translate("Model", "Transaction"))
        self.modelTabs.setTabText(self.modelTabs.indexOf(self.termialTab), _translate("Model", "Terminal"))
        self.modelTabs.setTabText(self.modelTabs.indexOf(self.serverTab), _translate("Model", "Server"))

