# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replace_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(614, 387)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.settingsLayout = QtWidgets.QHBoxLayout()
        self.settingsLayout.setObjectName("settingsLayout")
        self.leftSettingsLayout = QtWidgets.QVBoxLayout()
        self.leftSettingsLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.leftSettingsLayout.setSpacing(6)
        self.leftSettingsLayout.setObjectName("leftSettingsLayout")
        self.maskLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maskLabel.sizePolicy().hasHeightForWidth())
        self.maskLabel.setSizePolicy(sizePolicy)
        self.maskLabel.setObjectName("maskLabel")
        self.leftSettingsLayout.addWidget(self.maskLabel)
        self.containingLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.containingLabel.sizePolicy().hasHeightForWidth())
        self.containingLabel.setSizePolicy(sizePolicy)
        self.containingLabel.setObjectName("containingLabel")
        self.leftSettingsLayout.addWidget(self.containingLabel)
        self.directoryLabel = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directoryLabel.sizePolicy().hasHeightForWidth())
        self.directoryLabel.setSizePolicy(sizePolicy)
        self.directoryLabel.setObjectName("directoryLabel")
        self.leftSettingsLayout.addWidget(self.directoryLabel)
        self.settingsLayout.addLayout(self.leftSettingsLayout)
        self.rightSettingsLayout = QtWidgets.QVBoxLayout()
        self.rightSettingsLayout.setSpacing(6)
        self.rightSettingsLayout.setObjectName("rightSettingsLayout")
        self.maskComboBox = QtWidgets.QComboBox(Frame)
        self.maskComboBox.setEditable(True)
        self.maskComboBox.setObjectName("maskComboBox")
        self.rightSettingsLayout.addWidget(self.maskComboBox)
        self.textComboBox = QtWidgets.QComboBox(Frame)
        self.textComboBox.setEditable(True)
        self.textComboBox.setObjectName("textComboBox")
        self.rightSettingsLayout.addWidget(self.textComboBox)
        self.dirChooseLayout = QtWidgets.QHBoxLayout()
        self.dirChooseLayout.setObjectName("dirChooseLayout")
        self.chooseDirComboBox = QtWidgets.QComboBox(Frame)
        self.chooseDirComboBox.setEditable(True)
        self.chooseDirComboBox.setObjectName("chooseDirComboBox")
        self.dirChooseLayout.addWidget(self.chooseDirComboBox)
        self.chooseDirButton = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseDirButton.sizePolicy().hasHeightForWidth())
        self.chooseDirButton.setSizePolicy(sizePolicy)
        self.chooseDirButton.setMinimumSize(QtCore.QSize(30, 0))
        self.chooseDirButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.chooseDirButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chooseDirButton.setIconSize(QtCore.QSize(0, 0))
        self.chooseDirButton.setObjectName("chooseDirButton")
        self.dirChooseLayout.addWidget(self.chooseDirButton)
        self.rightSettingsLayout.addLayout(self.dirChooseLayout)
        self.settingsLayout.addLayout(self.rightSettingsLayout)
        self.settingsLayout.setStretch(1, 1)
        self.mainLayout.addLayout(self.settingsLayout)
        self.filesTable = QtWidgets.QTableWidget(Frame)
        self.filesTable.setObjectName("filesTable")
        self.filesTable.setColumnCount(3)
        self.filesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesTable.setHorizontalHeaderItem(2, item)
        self.filesTable.verticalHeader().setVisible(False)
        self.mainLayout.addWidget(self.filesTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.replceLabel = QtWidgets.QLabel(Frame)
        self.replceLabel.setObjectName("replceLabel")
        self.horizontalLayout.addWidget(self.replceLabel)
        self.replaceLineEdit = QtWidgets.QLineEdit(Frame)
        self.replaceLineEdit.setObjectName("replaceLineEdit")
        self.horizontalLayout.addWidget(self.replaceLineEdit)
        self.replaceButton = QtWidgets.QPushButton(Frame)
        self.replaceButton.setObjectName("replaceButton")
        self.horizontalLayout.addWidget(self.replaceButton)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.replaceProgressBar = QtWidgets.QProgressBar(Frame)
        self.replaceProgressBar.setProperty("value", 24)
        self.replaceProgressBar.setObjectName("replaceProgressBar")
        self.mainLayout.addWidget(self.replaceProgressBar)
        self.footerLayout = QtWidgets.QHBoxLayout()
        self.footerLayout.setObjectName("footerLayout")
        self.counterLabel = QtWidgets.QLabel(Frame)
        self.counterLabel.setObjectName("counterLabel")
        self.footerLayout.addWidget(self.counterLabel)
        self.findButton = QtWidgets.QPushButton(Frame)
        self.findButton.setBaseSize(QtCore.QSize(150, 0))
        self.findButton.setObjectName("findButton")
        self.footerLayout.addWidget(self.findButton)
        self.quitButton = QtWidgets.QPushButton(Frame)
        self.quitButton.setObjectName("quitButton")
        self.footerLayout.addWidget(self.quitButton)
        self.footerLayout.setStretch(0, 1)
        self.mainLayout.addLayout(self.footerLayout)
        self.verticalLayout_2.addLayout(self.mainLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.maskLabel.setText(_translate("Frame", "Mask"))
        self.containingLabel.setText(_translate("Frame", "Containing"))
        self.directoryLabel.setText(_translate("Frame", "Directory"))
        self.chooseDirButton.setText(_translate("Frame", "..."))
        item = self.filesTable.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "?"))
        item = self.filesTable.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "File Name"))
        item = self.filesTable.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "Size"))
        self.replceLabel.setText(_translate("Frame", "TextLabel"))
        self.replaceLineEdit.setPlaceholderText(_translate("Frame", "Insert text to replace..."))
        self.replaceButton.setText(_translate("Frame", "Replace"))
        self.counterLabel.setText(_translate("Frame", "TextLabel"))
        self.findButton.setText(_translate("Frame", "Find"))
        self.quitButton.setText(_translate("Frame", "Quit"))
